#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Azure Trusted Signing for Scrunch releases.
# Values land in tools/.cache/signing.env (gitignored) and, for CI, in the
# GitHub repository as secrets/variables read by .github/workflows/release.yml.
# ──────────────────────────────────────────────────────────────────────────

cd "$(dirname "$0")/.."
mkdir -p tools/.cache
ENV_FILE="tools/.cache/signing.env"
TOTAL_STAGES=7

banner "Scrunch code signing (Azure Trusted Signing)"

stage "Prerequisites"
say "Signing needs an Azure subscription (Trusted Signing Basic is about USD 10/month),"
say "the GitHub CLI logged in to the scrunch repository, and about 20 minutes plus"
say "Microsoft's identity validation wait (hours to a few days)."
step "Run 'gh auth status' in another terminal if unsure; secrets are skipped without it."
open_url "https://portal.azure.com/#view/Microsoft_Azure_Billing/SubscriptionsBladeV2"
step "Subscriptions: copy the Subscription ID you will pay from."
ask AZURE_SUBSCRIPTION_ID "Subscription ID:"
open_url "https://portal.azure.com/#view/Microsoft_AAD_IAM/TenantOverview.ReactView"
step "Microsoft Entra ID overview: copy the Tenant ID."
ask AZURE_TENANT_ID "Tenant ID:"
write_env AZURE_SUBSCRIPTION_ID "$AZURE_SUBSCRIPTION_ID"
write_env AZURE_TENANT_ID "$AZURE_TENANT_ID"

stage "Trusted Signing account"
open_url "https://portal.azure.com/#create/Microsoft.AzureCodeSigning"
step "Create: pick the subscription, a resource group (e.g. scrunch-signing), a"
step "region close to you (East US / West US 2 / West Europe / North Europe are common),"
step "an account name (lowercase, e.g. scrunch) and the Basic pricing tier. Review + create."
step "Open the new account. On its Overview, copy 'Account URI' (https://<region>.codesigning.azure.net)."
note "If the portal wording differs, look for the account's endpoint/URI on the Overview blade."
ask TRUSTED_SIGNING_ACCOUNT "Account name:"
ask TRUSTED_SIGNING_ENDPOINT "Account URI:"
write_env TRUSTED_SIGNING_ACCOUNT "$TRUSTED_SIGNING_ACCOUNT"
write_env TRUSTED_SIGNING_ENDPOINT "$TRUSTED_SIGNING_ENDPOINT"

stage "Identity validation"
say "Microsoft verifies who publishes the binaries; the validated name is what Windows"
say "shows users as the publisher. Individual validation needs a government ID and a"
say "matching legal name; Organization validation needs business registration details."
step "In the Trusted Signing account: Objects → Identity validations → New identity."
step "Choose Individual or Organization, fill in the form, submit, and complete the"
step "email/ID verification it sends. Status must read 'Completed' before the next stage."
warn "This can take days. Ctrl-C now and re-run this wizard once it is Completed; saved values are kept."
pause "Press Enter when identity validation shows Completed (or Ctrl-C to come back later)."

stage "Certificate profile"
step "In the account: Objects → Certificate profiles → Create → Public Trust."
step "Name it (e.g. scrunch-public), select the completed identity validation, and create."
ask TRUSTED_SIGNING_PROFILE "Certificate profile name:"
write_env TRUSTED_SIGNING_PROFILE "$TRUSTED_SIGNING_PROFILE"

stage "GitHub Actions identity (Entra app registration)"
say "CI signs with a workload identity, so no certificate or secret is stored in GitHub."
open_url "https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationsListBlade"
step "New registration → name 'scrunch-release-signing', single tenant, no redirect URI → Register."
step "On the app Overview copy the 'Application (client) ID'."
ask AZURE_CLIENT_ID "Application (client) ID:"
step "Certificates & secrets → Federated credentials → Add credential → 'GitHub Actions deploying Azure resources'."
step "Organization: your GitHub user/org (nickzonzh), Repository: scrunch, Entity type: Environment,"
step "Environment name: release, Name: github-release. Add."
note "The workflow only assumes this identity for v* tags, through the 'release' environment."
pause "Press Enter once the federated credential is saved."
write_env AZURE_CLIENT_ID "$AZURE_CLIENT_ID"

stage "Grant signing rights"
step "Back in the Trusted Signing account: Access control (IAM) → Add role assignment."
step "Role: 'Trusted Signing Certificate Profile Signer'. Members: the app 'scrunch-release-signing'."
step "Add the same role for your own user account so tools/release.ps1 can sign locally after 'az login'."
pause "Press Enter once both role assignments are saved."

stage "Publish to GitHub"
say "Repository secrets for the workflow's azure/login step and variables for the account."
set_secret AZURE_CLIENT_ID "$AZURE_CLIENT_ID"
set_secret AZURE_TENANT_ID "$AZURE_TENANT_ID"
set_secret AZURE_SUBSCRIPTION_ID "$AZURE_SUBSCRIPTION_ID"
set_var TRUSTED_SIGNING_ENDPOINT "$TRUSTED_SIGNING_ENDPOINT"
set_var TRUSTED_SIGNING_ACCOUNT "$TRUSTED_SIGNING_ACCOUNT"
set_var TRUSTED_SIGNING_PROFILE "$TRUSTED_SIGNING_PROFILE"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  gh api -X PUT "repos/{owner}/{repo}/environments/release" >/dev/null 2>&1 \
    && printf '  %s✓ ensured%s GitHub environment release\n' "$GREEN" "$RESET" \
    || { SKIPPED+=("GitHub environment 'release' (Settings → Environments → New environment)"); warn "could not create the release environment"; }
fi
say ""
say "Local signing: run 'az login', then in PowerShell:"
note "  . ./tools/trusted-signing.ps1 -Endpoint $TRUSTED_SIGNING_ENDPOINT -Account $TRUSTED_SIGNING_ACCOUNT -Profile $TRUSTED_SIGNING_PROFILE"
note "  ./tools/release.ps1 -RequireSigning"

finish
